name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3
    
      # Set up NodeJS
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install NPM dependencies
      - name: Install NPM dependencies
        run: npm install

      # Install SonarQube Scanner
      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      # SonarQube Analysis
      - name: SonarQube Analysis
        run: sonarqube-scanner \
          -Dsonar.projeckKey=sonar-github-actions-cicd \
          -Dsonar.sources=.\
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login= ${{ secrets.SONAR_TOKEN}}

      
